apiVersion: apps/v1
kind: Deployment
metadata:
  name: eyego-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eyego
  template:
    metadata:
      labels:
        app: eyego
    spec:
      containers:
      - name: eyego
        image: nagham94/eyego-image:latest
        ports:
        - containerPort: 3000
